### ISSUE TITLE
Wertpapier kaufen/verkaufen - Werte werden in der Oberfläche nicht aktualisiert

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#13]
Odervolumen, Ordergebühren und Gesamtkosten werden nicht aktualisiert
![US18](https://user-images.githubusercontent.com/32308465/60251339-a6c01c80-98c8-11e9-85a7-dc4e6c6050ec.png)

**Comment by Franzhose** [comment]
fixed with 5d23866390269386588203f1f81424e68c2ea5cb
