### ISSUE TITLE
Festgeld mit Kurs 0€

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#15]
Ich bin mir nicht sicher, ob es Sinn macht/korrekt ist, dass das Festgeld einen Kurs von 0€ hat. Sollte ein Teilnehmer sein Geld darin anlegen wollen, kauft er ja x*0€ und somit verändert sich sein Zahlungsmittelkonto ja nicht. Hab aber auch keine Option gefunden, den Kurs anzupassen.
![US19](https://user-images.githubusercontent.com/32308465/60254004-6747ff00-98cd-11e9-852e-2f621058e0c4.png)

**Comment by jackderblaueaffe** [comment]
gefixed
