### ISSUE TITLE
Fehler im Ablauf? (Periode abschließen, Wertpapiere kaufen)

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#17]
Mir ist aufgefallen, dass die Teilnehmer bereits Wertpapiere kaufen können, sobald die Periode gespeichert, jedoch noch nicht abgeschlossen ist. 
Ist das so korrekt? Wenn ja, dann haben wir das Problem, dass der ETF-Kurs und der Kurs der Aktien zu diesem Zeitpunkt noch nicht berechnet werden.
Nach Abschluss der Periode durch den Seminarleiter sind die Kurse dann berechnet. 
Vielleicht hab ich hier aber auch einen Denkfehler...
![US10+11](https://user-images.githubusercontent.com/32308465/60355755-757e4400-99cf-11e9-9787-0037b0945cd8.png)
![grafik](https://user-images.githubusercontent.com/32308465/60356251-d35f5b80-99d0-11e9-9565-634f038e5dd6.png)

**Comment by jcriecken** [comment]
Wäre es da nicht sinvoll nur Periode abschließen und nicht gar nicht speichern möglich zu machen ?

**Comment by KarelZe** [comment]
@jcriecken Nein, weil du zunächst die richtigen Kurse brauchst, zu denen gekauft werden kann und du am Ende der Periode die Abschlussbuchung machen willst.

**Comment by KarelZe** [comment]
Der Issue ist bereits in #36 mit drin und kann deshalb geschlossen werden.

**Comment by KarelZe** [comment]
Der Issue ist bereits in #36 mit drin und kann deshalb geschlossen werden.
