### ISSUE TITLE
Druck verändert UI Node

### ISSUE THREAD

**Issue by KarelZe** [KarelZe/DHBW_MWI#18]
**Problem:** Drucken verändert die UI-Node der Anzeige

![drucken](https://user-images.githubusercontent.com/12801659/60382888-effba200-9a69-11e9-9551-543baf9fabf2.gif)

**Lösung:** Node für Druck versuchen zu clonen und dann zu manipulieren.

**Comment by jcriecken** [comment]
node.getStyleClass().clear(); führt dazu, dass die Schrift nicht mehr lesbar ist. Damit die ursprüngliche node sich nicht mitverändert, werden jetzt keine Transformationen mehr durchgeführt --> Die node passt auch so gut in die Druckansicht....
