### ISSUE TITLE
Teilnehmer drucken druckt nicht alle Teilnehmer

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#19]
Nicht alle Teilnehmer im Dokument/Druck sichtbar
[Drucktest.pdf](https://github.com/KarelZe/DHBW_MWI/files/3342010/Drucktest.pdf)

**Comment by jcriecken** [comment]
Ich kriege das nicht hin, dass er unabhängig von Teilnehmeranzahl alle anzeigt. Ich habe die Tabelle jetzt soweit vergrößert, dass er zumindest immer die besten 10 drucken kann.
