### ISSUE TITLE
Anzahl / Volumen Wertpapier kaufen / verkaufen

### ISSUE THREAD

**Issue by KarelZe** [KarelZe/DHBW_MWI#22]
Christian und ich haben etwas gespielt. Dabei ist uns aufgefallen dass man anteilige Aktien und Anleihen kaufen kann.
**Richtig:**
> Aktien nur Ganzzahl von Mindestvolumen z. B. 1 Stück
> Anleihen nur Mindestvolumen von z. B. 1.000 EUR bzw. Vielfache davon, also auch keine 1.050 EUR
> Festgeld beliebig

Ggf. kannst du die Oberfläche auch anpassen, sodass unterschiedliche Felder angeboten werden, je nach Wertpapierart z. B. Anleihe heißt das dann Nominalvolumen, bei Aktien Stückzahl etc.

**Comment by KarelZe** [comment]
@Franzhose ist glaub deiner, oder? 😉

**Comment by Franzhose** [comment]
fixed with 5d23866390269386588203f1f81424e68c2ea5cb
