### ISSUE TITLE
Was passiert mit Aktien und Anleihen mit Kurs 0? 

### ISSUE THREAD

**Issue by KarelZe** [KarelZe/DHBW_MWI#26]
Es ist festzulegen, wie mit Pleiteunternehmen umzugehen ist. Werden diese Aktien vom `Kauf` ausgesetzt?

Diese ist in dem Fachkonzept Kauf / Rendite festzulegen.

**Comment by Franzhose** [comment]
fixed with 6987bbdf430a5f63012a7bc600f369893d69b46e

Anleihen und Aktien werden mit Kurs 0 ausgeblendet und somit vom kauf und Verkauf ausgesetzt. Sobald sich der Kurs wieder ändert, sind sie wieder handelbar.
