### ISSUE TITLE
Kurs von Anleihen falsch berechnet

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#28]
Ich habe verschiedene Werte für den manuellen Kurs und den Spread einer Anleihe ausprobiert, jedoch wird in der DB immer der gleiche Kurs abgespeichert.
![grafik](https://user-images.githubusercontent.com/32308465/60606512-cb7e2d80-9dbb-11e9-8387-5d9860cf1a75.png)

**Comment by MrApplebyte** [comment]
Ich hab's jetzt mal mit extremen Werten versucht. Kapitalmarktzins und Spread auf 50%. Die Kurse stimmen dann nicht überein.
![grafik](https://user-images.githubusercontent.com/32308465/60761152-047c0380-a043-11e9-9336-c9ed03dc5c57.png)

**Comment by MrApplebyte** [comment]
Bei jeweils 2% stimmt es leider auch nicht. Verwende ich falsche Werte?
![grafik](https://user-images.githubusercontent.com/32308465/60761173-8835f000-a043-11e9-81d2-5796e13e397a.png)

**Comment by KarelZe** [comment]
**Fall 1**
![grafik](https://user-images.githubusercontent.com/12801659/60762072-b1f91200-a057-11e9-90cf-38d78225eb3f.png)
![grafik](https://user-images.githubusercontent.com/12801659/60762084-0b614100-a058-11e9-8921-f61c2716b80f.png)
![grafik](https://user-images.githubusercontent.com/12801659/60762082-fab0cb00-a057-11e9-8044-d1ac3db6ad24.png)
**Fall 2**
![grafik](https://user-images.githubusercontent.com/12801659/60762093-5f6c2580-a058-11e9-9a84-328fe5bbef20.png)
![grafik](https://user-images.githubusercontent.com/12801659/60762099-7448b900-a058-11e9-8a67-98f0c34e1edf.png)
![grafik](https://user-images.githubusercontent.com/12801659/60762102-8296d500-a058-11e9-835f-fa3ebc7a7f7f.png)

@MrApplebyte 
Für mich sind beide Berechnungen damit korrekt. Vermute mal, dass du den Spread beim Emission und den aktuellen Spread verwechselt hast. Das sind zwei paar Stiefel. Daher schließe ich den Issue. :tada:
