### ISSUE TITLE
Aktualisierung der Bestenliste mit den aktuellen Portfoliowerten

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#29]
In welchem Schritt wird die Bestenliste mit den aktuellen Portfoliowerten aktualisiert? 
Ich habe mit einem Teilnehmer in Periode 1 eine Aktie gekauft, deren Wert ich mehrere Perioden danach weiter erhöht habe. In der Bestenliste steht jedoch nur der Portfoliowert aus Periode 1, nach dem 1. Kauf.
(Der Wert müsste weit über 1.000€ sein.)
![grafik](https://user-images.githubusercontent.com/32308465/60607480-a094d900-9dbd-11e9-91f7-864d9a2d7644.png)

**Comment by jcriecken** [comment]
Das wird durch portfolioFassade.getGesamtSaldo(BENUTZERID); im Benutzer Print Model gemacht.

Kann es sein, dass die Gewinne erst nach veräußern der Aktie da sind ?

**Comment by jcriecken** [comment]
@KarelZe

**Comment by KarelZe** [comment]
Der @Franzhose wollte meines Wissens nach an der Portfolio-Fassade noch Anpassungen vornehmen. Dabei ging es auch um den aktuellen Bestand vs. Volumen. Er ist damit eher der richtige Ansprechpartner. Werde mich daher entfernen.

**Comment by Franzhose** [comment]
fixed with 6987bbdf430a5f63012a7bc600f369893d69b46e
