### ISSUE TITLE
Installer lässt sich nicht packen

### ISSUE THREAD

**Issue by KarelZe** [KarelZe/DHBW_MWI#30]
Laut Recherche von Max und Christian gibt es Probleme bei der Zusammenstellung eines Installers.

**Comment by Franzhose** [comment]
@KarelZe 
leider nein, aber ich hab mal nen kumpel angeschrieben, vlt. kann der da helfen.

**Comment by MrApplebyte** [comment]
Da wir hier keine Lösung gefunden haben, werden wir, wie gestern besprochen, den Auftraggebern im Nachgang über die Installation von IntelliJ IDEA die Software zur Verfügung stellen.
