### ISSUE TITLE
Sammel Issue Perioden Pflegen

### ISSUE THREAD

**Issue by Franzhose** [KarelZe/DHBW_MWI#36]
Mir sind mehrere Dinge aufgefallen:
1. Aktiver Tab wird bei Laden der Seite nicht gehighlighted. ☑️ 
2. Periode kann nach abschließen noch verändert werden. Ist es möglich den Tab auszugrauen?☑️ 
3. TransaktionsartId hat wert null bei festgeldverzinsung in der Buchungstabelle // erzeugt nullpointerexceptions bei wertpapier_verkaufen  ☑️ 
4. Prüfen, dass Feld `Manueller Kurs` optional zu machen.:x:
5. Prüfen, ob berechneter Kurs angezeigt werden kann. ❓ 
6. Sicherstellen, dass Anwender einen `Spread` erfasst. Wenn Anwender keinen Wert explizit in den Spread eingibt, wird bei Spread null in die Datenbank eingetragen, das führt dazu, dass in Zeile 34 vom FloatingRateNoteModel eine NullPointerException fliegt. ☑️ 
7. Periode kann nach erneutem Aufruf wieder und wieder gepflegt werden. :x:
8. Inkonsistentes Layout.☑️
9. Überprüfung, ob Bewertungszeitpunkt für Floater und ETF korrekt ist.☑️ 
10. Manueller Kurs von z. B. `101` als `101` und nicht als `1.01` speichern. ☑️

**Comment by KarelZe** [comment]
**Zu 6.**
Ist gelöst mit b75ee809a7e9d30efadb494967acdd92fabd8a3a. Ich habe mich dazu entschieden, bei Anlage einer neuen Periode den Spread für Anleihen mit `0` zu setzen. Dies ermöglicht, dass der Spread weiterhin `nullable` ist. Gleichzeitig ist sichergestellt, dass alle Anleihen einen Spread haben.
Dies ist zugleich die einzige Stelle, wo Kurse angelegt werden, weshalb ich es dort aufgenommen habe.
Jetzt informiert auch eine Fehlermeldung über einen ungültigen Spread bzw. alle Falscheingaben.

@Franzhose @jackderblaueaffe Passt so für euch?

**Comment by KarelZe** [comment]
Werde Issue schließen. Für Dokumentation hinsichtlich Bearbeitung siehe https://github.com/KarelZe/DHBW_MWI/issues/36#issuecomment-508924690. @Franzhose @jackderblaueaffe @MrApplebyte  bitte meldet euch, falls euch beim Testen was auffällt und macht den Issue wieder auf. Herzlichen Dank. 🎉
