### ISSUE TITLE
NullPointerException bei Floaterbewertung

### ISSUE THREAD

**Issue by jackderblaueaffe** [KarelZe/DHBW_MWI#39]
**Problem:** Wenn man bei Periode pflegen keinen Wert explizit in den Spread eingibt, wird bei Spread `null` in die Datenbank eingetragen, das führt dazu, dass in Zeile 34 vom FloatingRateNoteModel eine NullPointerException fliegt.
**Lösung:** evtl. An der Oberfläche sichergestellen, dass ein Spread eingetragen wird.

**Comment by KarelZe** [comment]
OK, werde das mir gleich anschauen.

**Comment by KarelZe** [comment]
Weiterbearbeitung in #36, da teilweise redundant und Bearbeitung jeweils durch mich erfolgt.

**Comment by KarelZe** [comment]
Weiterbearbeitung in #36, da teilweise redundant und Bearbeitung jeweils durch mich erfolgt.
