### ISSUE TITLE
Ausschüttungen funktionieren nicht

### ISSUE THREAD

**Issue by jackderblaueaffe** [KarelZe/DHBW_MWI#40]
Problem: bezugsgröße hat falschen Wert
z.B.: Kauf zu 10.000 €
Ausschüttung nächste Periode (5%): 10.000 * 5 % = 500 € (funktioniert)
Ausschüttung nächste Periode (5%): 10.000 + 500 (Ausschüttung von vorheriger Periode, da gleiche WertpapierID und die Portfoliofassade dieses auch zurückliefert) > 500 € -> falscher Wert
gleiches gilt für Verkaufen

**Comment by jackderblaueaffe** [comment]
Problem: bezugsgröße hat falschen Wert
z.B.: Kauf zu 10.000 €
Ausschüttung nächste Periode (5%): 10.000 * 5 % = 500 € (funktioniert)
Ausschüttung nächste Periode (5%): 10.000 + 500 (Ausschüttung von vorheriger Periode, da gleiche WertpapierID und die Portfoliofassade dieses auch zurückliefert) > 500 € -> falscher Wert
gleiches gilt für Verkaufen

**Comment by KarelZe** [comment]
Die Verbuchung geht grundsätzlich. Siehe https://github.com/KarelZe/DHBW_MWI/issues/35#issuecomment-508621068. Allerdings ist m. E. das einzige was geändert werden müsste, dass bei `ZinsbuchungAnleihe` und `ZinsbuchungFestgeld` `buchung.setVolumen(0);` sein.

**Comment by jackderblaueaffe** [comment]
funktioniert nun fehlerfrei
