### ISSUE TITLE
Depotübersicht wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by MrApplebyte** [KarelZe/DHBW_MWI#44]
Ich bin nach anlegen der 4. Periode in die Depotübersicht. Dann hab ich eine IndexOutofbounds Exception erhalten. Weiß nicht genau, wie das Problem zu reproduzieren ist; bin zufällig darauf gestoßen. Bin beim debuggen auch nicht schlauer geworden
![grafik](https://user-images.githubusercontent.com/32308465/60761369-2d9e9300-a047-11e9-8b9f-4a16a404af94.png)

**Comment by Franzhose** [comment]
alles klar, schau ich mir an

**Comment by Franzhose** [comment]
fixed with 6987bbdf430a5f63012a7bc600f369893d69b46e
